# Valkyrie v 1.3 by 754503921
# http://www.mcbbs.net/thread-681010-1-1.html
# 如果要启用 Valkyrie 的更新检测，请将 enableValkyrieUpdateCheck 设置为 true
# 如果要启用拓展的更新检测，请将 enableExtensionUpdateCheck 设置为 true
enableValkyrieUpdateCheck: false
enableExtensionUpdateCheck: false